server:
  port: 8080

spring:
  mvc.hiddenmethod.filter.enabled: true
  thymeleaf:
    cache: false
    mode: HTML5

  # Data base
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/books?useUnicode=true&serverTimezone=UTC&useSSL=true&verifyServerCertificate=false"
    username: "root"
    password: "123456"

  # Flyway
  flyway:
    url: "jdbc:mysql://localhost:3306/books?useSSL=false&serverTimezone=UTC&useUnicode=true"
    schemas: "books"
    user: "root"
    password: "123456"
    enabled: true
    table: "schema_migration"
