spring:
  thymeleaf:
    cache: false
    mode: HTML5

  datasource:
    url: jdbc:h2:mem:bookdb
    username: user
    password: book123
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql

    jpa:
      generate-ddl: false
      hibernate:
        ddl-auto: none
      show-sql: true

    h2:
      console:
        path: /h2-console
        settings:
          web-allow-others: false

server:
  port: 8080